export const mecatol = { name: "Mecatol Rex", resources: 1, influence: 6 };

const planets = [
  { name: "Jord", resources: 4, influence: 2 },
  { name: "Arinam", resources: 1, influence: 2 },
  { name: "Meer", resources: 0, influence: 4 },
  { name: "Lodor", resources: 3, influence: 1 },
  { name: "Industrex", resources: 2, influence: 3 },
  { name: "Thibah", resources: 1, influence: 1 },
  { name: "Corneeq", resources: 1, influence: 2 },
  { name: "Resculon", resources: 2, influence: 0 },
  { name: "Lazar", resources: 1, influence: 0 },
  { name: "Sakulag", resources: 2, influence: 1 },
  { name: "Quann", resources: 2, influence: 1 },
  { name: "Mallice", resources: 0, influence: 3 },
  { name: "Hope's End", resources: 3, influence: 0 },
  { name: "Wren Terra", resources: 2, influence: 2 },
  { name: "Archon Vail", resources: 1, influence: 3 },
  { name: "Wellon", resources: 1, influence: 2 },
  { name: "Bereg", resources: 3, influence: 1 },
  { name: "Lirta IV", resources: 2, influence: 3 },
  { name: "Mellon", resources: 0, influence: 2 },
  { name: "Shalloq", resources: 2, influence: 0 },
  { name: "Vefut II", resources: 2, influence: 2 },
  { name: "Centauri", resources: 1, influence: 3 },
  { name: "Gral", resources: 1, influence: 1 },
  { name: "Elysium", resources: 2, influence: 0 },
  { name: "Ixth", resources: 0, influence: 3 },
  { name: "New Albion", resources: 1, influence: 1 },
  { name: "Starpoint", resources: 3, influence: 2 },
  { name: "Vega Major", resources: 2, influence: 1 },
  { name: "Vega Minor", resources: 1, influence: 2 },
  { name: "Arcturus", resources: 3, influence: 1 },
  { name: "Bellatrix", resources: 0, influence: 1 },
  { name: "Corman", resources: 0, influence: 2 },
  { name: "Arnor", resources: 1, influence: 2 },
  { name: "Lor", resources: 2, influence: 1 },
  { name: "Tren'lak", resources: 1, influence: 0 },
  { name: "Ba'kal", resources: 3, influence: 2 },
  { name: "Kraag", resources: 0, influence: 1 },
  { name: "Tequ'ran", resources: 2, influence: 0 },
  { name: "Torkan", resources: 0, influence: 3 },
  { name: "Saudor", resources: 2, influence: 2 },
  { name: "Mehar Xull", resources: 1, influence: 1 },
  { name: "Rarron", resources: 0, influence: 3 },
  { name: "Rigel I", resources: 1, influence: 1 },
  { name: "Rigel II", resources: 2, influence: 2 },
  { name: "Rigel III", resources: 0, influence: 2 },
  { name: "Thibah", resources: 1, influence: 1 },
  { name: "Hopesend", resources: 3, influence: 0 },
];

export default planets;
